name: gis
channels:
- anaconda
- conda-forge
dependencies:
- python=3.6
- matplotlib
- rasterio
- numpy
- shapely
- fiona
- geopandas
- pandas
- pycrs
- xlrd
- ipdb
- keras
- seaborn
- scikit-learn
- google-cloud-storage

